name: Release (lib)

on:
  release:
    types:
    - released

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    working-directory: ./cmri

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write     # Required to add files to release
      id-token: write     # Required for OIDC token exchange
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Package
      run: cargo package
    - name: Attach
      run: gh release upload  --repo "${{ github.repository }}" "${{ github.ref_name }}" ../target/package/cmri-*.crate
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
